# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/chooseDesign_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(991, 615)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.bck_btn = QtWidgets.QPushButton(Form)
        self.bck_btn.setMinimumSize(QtCore.QSize(31, 39))
        self.bck_btn.setMaximumSize(QtCore.QSize(31, 39))
        self.bck_btn.setStyleSheet("background-color: rgb(255, 170, 0,4);")
        self.bck_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/images/icons8-back-67.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bck_btn.setIcon(icon)
        self.bck_btn.setIconSize(QtCore.QSize(31, 39))
        self.bck_btn.setObjectName("bck_btn")
        self.gridLayout_2.addWidget(self.bck_btn, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(386, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setMaximumSize(QtCore.QSize(271, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(386, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 3, 1, 1)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem2 = QtWidgets.QSpacerItem(163, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 0, 1, 1)
        self.clientDesign_btn = QtWidgets.QPushButton(self.frame)
        self.clientDesign_btn.setMinimumSize(QtCore.QSize(110, 40))
        self.clientDesign_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.clientDesign_btn.setStyleSheet("font: 11pt \"Acumin Pro\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(50, 85, 127);\n"
"\n"
" border-radius: 12px;\n"
"")
        self.clientDesign_btn.setObjectName("clientDesign_btn")
        self.gridLayout.addWidget(self.clientDesign_btn, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(163, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 1, 4, 1, 1)
        self.officeDesign_btn = QtWidgets.QPushButton(self.frame)
        self.officeDesign_btn.setMinimumSize(QtCore.QSize(215, 40))
        self.officeDesign_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.officeDesign_btn.setStyleSheet("font: 11pt \"Acumin Pro\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(50, 85, 127);\n"
"\n"
" border-radius: 12px;\n"
"")
        self.officeDesign_btn.setObjectName("officeDesign_btn")
        self.gridLayout.addWidget(self.officeDesign_btn, 1, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 97, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 3, 1, 1, 1)
        self.filaPath_lbl = QtWidgets.QLabel(self.frame)
        self.filaPath_lbl.setMinimumSize(QtCore.QSize(215, 0))
        self.filaPath_lbl.setMaximumSize(QtCore.QSize(16777215, 30))
        self.filaPath_lbl.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"font: 8pt \"Acumin Pro\";\n"
"padding-bottom:7px;")
        self.filaPath_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.filaPath_lbl.setObjectName("filaPath_lbl")
        self.gridLayout.addWidget(self.filaPath_lbl, 2, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem6, 0, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem7, 0, 3, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 1, 0, 1, 4)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "أمر شغل جديد"))
        self.clientDesign_btn.setText(_translate("Form", "تصميم العميل"))
        self.officeDesign_btn.setText(_translate("Form", "تصميم بالمكتب"))
        self.filaPath_lbl.setText(_translate("Form", "مسار الملف"))
import app_resources_rc
