# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/followOrder_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1920, 1077)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        Form.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridLayout_3 = QtWidgets.QGridLayout(Form)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMaximumSize(QtCore.QSize(160, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setObjectName("gridLayout")
        self.edit_btn = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_btn.sizePolicy().hasHeightForWidth())
        self.edit_btn.setSizePolicy(sizePolicy)
        self.edit_btn.setMinimumSize(QtCore.QSize(100, 40))
        self.edit_btn.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Acumin Pro")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.edit_btn.setFont(font)
        self.edit_btn.setStyleSheet("\n"
" transition-duration: 0.4s;\n"
" color: white;\n"
" background-color :rgb(50, 85, 127);\n"
" border: 2px solid #rgb(50, 85, 127)\n"
"\n"
" box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24), 0 17px 50px 0 rgba(0,0,0,0.19);")
        self.edit_btn.setObjectName("edit_btn")
        self.gridLayout.addWidget(self.edit_btn, 2, 0, 1, 1)
        self.print_btn = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.print_btn.sizePolicy().hasHeightForWidth())
        self.print_btn.setSizePolicy(sizePolicy)
        self.print_btn.setMinimumSize(QtCore.QSize(100, 40))
        self.print_btn.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Acumin Pro")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.print_btn.setFont(font)
        self.print_btn.setStyleSheet("\n"
" transition-duration: 0.4s;\n"
" color: white;\n"
" background-color :rgb(50, 85, 127);\n"
" border: 2px solid #rgb(50, 85, 127)\n"
"\n"
" box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24), 0 17px 50px 0 rgba(0,0,0,0.19);")
        self.print_btn.setObjectName("print_btn")
        self.gridLayout.addWidget(self.print_btn, 4, 0, 1, 1)
        self.delete_btn = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delete_btn.sizePolicy().hasHeightForWidth())
        self.delete_btn.setSizePolicy(sizePolicy)
        self.delete_btn.setMinimumSize(QtCore.QSize(100, 40))
        self.delete_btn.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Acumin Pro")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.delete_btn.setFont(font)
        self.delete_btn.setStyleSheet("\n"
" transition-duration: 0.4s;\n"
" color: white;\n"
" background-color :rgb(50, 85, 127);\n"
" border: 2px solid #rgb(50, 85, 127)\n"
"\n"
" box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24), 0 17px 50px 0 rgba(0,0,0,0.19);")
        self.delete_btn.setObjectName("delete_btn")
        self.gridLayout.addWidget(self.delete_btn, 3, 0, 1, 1)
        self.new_btn = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.new_btn.sizePolicy().hasHeightForWidth())
        self.new_btn.setSizePolicy(sizePolicy)
        self.new_btn.setMinimumSize(QtCore.QSize(100, 40))
        self.new_btn.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Acumin Pro")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.new_btn.setFont(font)
        self.new_btn.setStyleSheet("\n"
" transition-duration: 0.4s;\n"
" color: white;\n"
" background-color :rgb(50, 85, 127);\n"
" border: 2px solid #rgb(50, 85, 127)\n"
"\n"
" box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24), 0 17px 50px 0 rgba(0,0,0,0.19);")
        self.new_btn.setObjectName("new_btn")
        self.gridLayout.addWidget(self.new_btn, 1, 0, 1, 1)
        self.end_btn = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.end_btn.sizePolicy().hasHeightForWidth())
        self.end_btn.setSizePolicy(sizePolicy)
        self.end_btn.setMinimumSize(QtCore.QSize(100, 40))
        self.end_btn.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Acumin Pro")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.end_btn.setFont(font)
        self.end_btn.setStyleSheet("\n"
" transition-duration: 0.4s;\n"
" color: white;\n"
" background-color :rgb(50, 85, 127);\n"
" border: 2px solid #rgb(50, 85, 127)\n"
"\n"
" box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24), 0 17px 50px 0 rgba(0,0,0,0.19);")
        self.end_btn.setObjectName("end_btn")
        self.gridLayout.addWidget(self.end_btn, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_2, 0, 0, 2, 1)
        spacerItem = QtWidgets.QSpacerItem(135, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        self.next_btn = QtWidgets.QPushButton(self.frame)
        self.next_btn.setMinimumSize(QtCore.QSize(91, 41))
        self.next_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.next_btn.setStyleSheet("font: 14pt \"Acumin Pro\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(50, 85, 127, 250);\n"
"\n"
" border-radius: 7px;\n"
"")
        self.next_btn.setObjectName("next_btn")
        self.gridLayout_2.addWidget(self.next_btn, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 3, 1, 1)
        self.dateEdit_2 = QtWidgets.QDateEdit(self.frame)
        self.dateEdit_2.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Acumin Pro")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.dateEdit_2.setFont(font)
        self.dateEdit_2.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"font: 11pt \"Acumin Pro\";\n"
"padding-bottom:7px;")
        self.dateEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit_2.setDateTime(QtCore.QDateTime(QtCore.QDate(2022, 6, 6), QtCore.QTime(0, 0, 0)))
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.gridLayout_2.addWidget(self.dateEdit_2, 0, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 5, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 6, 1, 1)
        self.dateEdit = QtWidgets.QDateEdit(self.frame)
        self.dateEdit.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Acumin Pro")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.dateEdit.setFont(font)
        self.dateEdit.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"font: 11pt \"Acumin Pro\";\n"
"padding-bottom:7px;")
        self.dateEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2022, 6, 6), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout_2.addWidget(self.dateEdit, 0, 7, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 8, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 0, 9, 1, 1)
        self.search_lineEdit = QtWidgets.QLineEdit(self.frame)
        self.search_lineEdit.setMinimumSize(QtCore.QSize(401, 35))
        self.search_lineEdit.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"\n"
"padding-bottom:7px;\n"
"font: 14pt \"Acumin Pro\";")
        self.search_lineEdit.setObjectName("search_lineEdit")
        self.gridLayout_2.addWidget(self.search_lineEdit, 0, 10, 1, 1)
        self.listWidget = QtWidgets.QListWidget(self.frame)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.listWidget.setFont(font)
        self.listWidget.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.listWidget.setStyleSheet("background-color: rgb(255, 255, 255,100);")
        self.listWidget.setTextElideMode(QtCore.Qt.ElideRight)
        self.listWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.listWidget.setMovement(QtWidgets.QListView.Static)
        self.listWidget.setFlow(QtWidgets.QListView.TopToBottom)
        self.listWidget.setViewMode(QtWidgets.QListView.ListMode)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_2.addWidget(self.listWidget, 1, 1, 1, 10)
        self.gridLayout_3.addWidget(self.frame, 1, 0, 1, 6)
        spacerItem4 = QtWidgets.QSpacerItem(813, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setMaximumSize(QtCore.QSize(271, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 1, 1, 4)
        self.details_btn = QtWidgets.QPushButton(Form)
        self.details_btn.setMinimumSize(QtCore.QSize(200, 60))
        self.details_btn.setMaximumSize(QtCore.QSize(200, 60))
        self.details_btn.setStyleSheet("font: 14pt \"Acumin Pro\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(50, 85, 127, 250);\n"
"\n"
" border-radius: 7px;\n"
"")
        self.details_btn.setObjectName("details_btn")
        self.gridLayout_3.addWidget(self.details_btn, 2, 4, 1, 2)
        spacerItem5 = QtWidgets.QSpacerItem(813, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 0, 5, 1, 1)
        self.bck_btn = QtWidgets.QPushButton(Form)
        self.bck_btn.setMinimumSize(QtCore.QSize(200, 60))
        self.bck_btn.setMaximumSize(QtCore.QSize(200, 60))
        self.bck_btn.setStyleSheet("font: 14pt \"Acumin Pro\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(50, 85, 127, 250);\n"
"\n"
" border-radius: 7px;\n"
"")
        self.bck_btn.setObjectName("bck_btn")
        self.gridLayout_3.addWidget(self.bck_btn, 2, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem6, 2, 3, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.edit_btn.setText(_translate("Form", "تعديل"))
        self.print_btn.setText(_translate("Form", "طباعة"))
        self.delete_btn.setText(_translate("Form", "مسح"))
        self.new_btn.setText(_translate("Form", "جديد"))
        self.end_btn.setText(_translate("Form", "انتهى"))
        self.next_btn.setText(_translate("Form", "بحث"))
        self.dateEdit_2.setDisplayFormat(_translate("Form", "yyyy-M-d"))
        self.label_3.setText(_translate("Form", "الي"))
        self.dateEdit.setDisplayFormat(_translate("Form", "yyyy-M-d"))
        self.label_2.setText(_translate("Form", "من"))
        self.search_lineEdit.setPlaceholderText(_translate("Form", "    بحث . . ."))
        self.label.setText(_translate("Form", "متابعة امر الشغل"))
        self.details_btn.setText(_translate("Form", "تفاصيل الامر"))
        self.bck_btn.setText(_translate("Form", "الرجوع"))
import app_resources_rc
