# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/main_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main(object):
    def setupUi(self, main):
        main.setObjectName("main")
        main.resize(1920, 1068)
        main.setMinimumSize(QtCore.QSize(0, 0))
        main.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label = QtWidgets.QLabel(main)
        self.label.setGeometry(QtCore.QRect(710, 30, 271, 51))
        self.label.setMaximumSize(QtCore.QSize(271, 71))
        font = QtGui.QFont()
        font.setFamily("Thunder Lord")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(main)
        self.frame.setGeometry(QtCore.QRect(1170, 100, 681, 811))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 24, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 1, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.ordersReq_btn = QtWidgets.QPushButton(self.frame)
        self.ordersReq_btn.setMinimumSize(QtCore.QSize(161, 161))
        self.ordersReq_btn.setMaximumSize(QtCore.QSize(161, 161))
        self.ordersReq_btn.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: rgb(85, 132, 220,100);\n"
"    color: #FFFFFF;\n"
"    padding: 2px;\n"
"    font: bold 15px;\n"
"    border-width: 6px;\n"
"    border-radius: 10px;\n"
"    border-color: #2752B8;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #EFEAD8;\n"
"}")
        self.ordersReq_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-important-delivery-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ordersReq_btn.setIcon(icon)
        self.ordersReq_btn.setIconSize(QtCore.QSize(100, 100))
        self.ordersReq_btn.setObjectName("ordersReq_btn")
        self.verticalLayout_4.addWidget(self.ordersReq_btn)
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setMaximumSize(QtCore.QSize(161, 16777215))
        font = QtGui.QFont()
        font.setFamily("Thunder Lord")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_4.addWidget(self.label_11)
        self.gridLayout.addLayout(self.verticalLayout_4, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 24, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 3, 4, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.clients_btn = QtWidgets.QPushButton(self.frame)
        self.clients_btn.setMinimumSize(QtCore.QSize(161, 161))
        self.clients_btn.setMaximumSize(QtCore.QSize(161, 161))
        self.clients_btn.setStyleSheet("QPushButton {\n"
"\n"
"    background-color: rgb(17, 43, 60,100);\n"
"    color: #FFFFFF;\n"
"    padding: 2px;\n"
"    font: bold 15px;\n"
"    border-width: 6px;\n"
"    border-radius: 10px;\n"
"    border-color: #2752B8;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #EFEAD8;\n"
"}")
        self.clients_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clients_btn.setIcon(icon1)
        self.clients_btn.setIconSize(QtCore.QSize(100, 100))
        self.clients_btn.setObjectName("clients_btn")
        self.verticalLayout.addWidget(self.clients_btn)
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setMaximumSize(QtCore.QSize(161, 16777215))
        font = QtGui.QFont()
        font.setFamily("Thunder Lord")
        font.setPointSize(19)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.gridLayout.addLayout(self.verticalLayout, 2, 3, 1, 2)
        spacerItem3 = QtWidgets.QSpacerItem(104, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 4, 2, 1, 2)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.followOrders_btn = QtWidgets.QPushButton(self.frame)
        self.followOrders_btn.setMinimumSize(QtCore.QSize(161, 161))
        self.followOrders_btn.setMaximumSize(QtCore.QSize(161, 161))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.followOrders_btn.setFont(font)
        self.followOrders_btn.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: rgb(149, 209, 204,100);\n"
"    color: #FFFFFF;\n"
"    padding: 2px;\n"
"    font: bold 15px;\n"
"    border-width: 6px;\n"
"    border-radius: 10px;\n"
"    border-color: #2752B8;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #EFEAD8;\n"
"}")
        self.followOrders_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-printer-maintenance-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.followOrders_btn.setIcon(icon2)
        self.followOrders_btn.setIconSize(QtCore.QSize(150, 150))
        self.followOrders_btn.setObjectName("followOrders_btn")
        self.verticalLayout_5.addWidget(self.followOrders_btn)
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setMaximumSize(QtCore.QSize(161, 16777215))
        font = QtGui.QFont()
        font.setFamily("Thunder Lord")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_5.addWidget(self.label_12)
        self.gridLayout.addLayout(self.verticalLayout_5, 4, 4, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(44, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 2, 2, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.finishedOrders_btn = QtWidgets.QPushButton(self.frame)
        self.finishedOrders_btn.setMinimumSize(QtCore.QSize(161, 161))
        self.finishedOrders_btn.setMaximumSize(QtCore.QSize(161, 161))
        self.finishedOrders_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(178, 39, 39,100);\n"
"    color: #FFFFFF;\n"
"    padding: 2px;\n"
"    font: bold 15px;\n"
"    border-width: 6px;\n"
"    border-radius: 10px;\n"
"    border-color: #2752B8;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #827397;\n"
"}")
        self.finishedOrders_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/list.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.finishedOrders_btn.setIcon(icon3)
        self.finishedOrders_btn.setIconSize(QtCore.QSize(100, 100))
        self.finishedOrders_btn.setObjectName("finishedOrders_btn")
        self.verticalLayout_3.addWidget(self.finishedOrders_btn)
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setMaximumSize(QtCore.QSize(161, 16777215))
        font = QtGui.QFont()
        font.setFamily("Thunder Lord")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_3.addWidget(self.label_10)
        self.gridLayout.addLayout(self.verticalLayout_3, 4, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 4, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.workOrder_btn = QtWidgets.QPushButton(self.frame)
        self.workOrder_btn.setMinimumSize(QtCore.QSize(161, 161))
        self.workOrder_btn.setMaximumSize(QtCore.QSize(16777215, 161))
        self.workOrder_btn.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: rgb(0, 110, 127,100);\n"
"    color: #FFFFFF;\n"
"    padding: 2px;\n"
"    font: bold 15px;\n"
"    border-width: 6px;\n"
"    border-radius: 10px;\n"
"    border-color: #2752B8;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #A0BCC2;\n"
"}")
        self.workOrder_btn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-add-list-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.workOrder_btn.setIcon(icon4)
        self.workOrder_btn.setIconSize(QtCore.QSize(400, 400))
        self.workOrder_btn.setObjectName("workOrder_btn")
        self.verticalLayout_2.addWidget(self.workOrder_btn)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem6 = QtWidgets.QSpacerItem(44, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setMaximumSize(QtCore.QSize(161, 16777215))
        font = QtGui.QFont()
        font.setFamily("Thunder Lord")
        font.setPointSize(21)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        spacerItem7 = QtWidgets.QSpacerItem(44, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 4)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem8, 2, 5, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem9, 4, 5, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem10, 0, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem11, 0, 5, 1, 1)
        self.logOut_btn = QtWidgets.QPushButton(main)
        self.logOut_btn.setGeometry(QtCore.QRect(20, 20, 50, 50))
        self.logOut_btn.setMinimumSize(QtCore.QSize(50, 50))
        self.logOut_btn.setMaximumSize(QtCore.QSize(50, 50))
        self.logOut_btn.setStyleSheet("background-color: rgb(0, 0, 0,0);")
        self.logOut_btn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/logo/images/icons8-logout-80.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logOut_btn.setIcon(icon5)
        self.logOut_btn.setIconSize(QtCore.QSize(50, 50))
        self.logOut_btn.setObjectName("logOut_btn")
        self.label_3 = QtWidgets.QLabel(main)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.label_3.setMinimumSize(QtCore.QSize(1920, 1080))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/login/images/backgroung/3433814.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.groupBox = QtWidgets.QGroupBox(main)
        self.groupBox.setGeometry(QtCore.QRect(10, 860, 341, 87))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.username_lbl = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.username_lbl.setFont(font)
        self.username_lbl.setStyleSheet("")
        self.username_lbl.setObjectName("username_lbl")
        self.gridLayout_3.addWidget(self.username_lbl, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("")
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 1, 0, 1, 1)
        self.sessionTime_lbl = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sessionTime_lbl.setFont(font)
        self.sessionTime_lbl.setStyleSheet("")
        self.sessionTime_lbl.setObjectName("sessionTime_lbl")
        self.gridLayout_3.addWidget(self.sessionTime_lbl, 1, 1, 1, 1)
        self.exit_btn = QtWidgets.QPushButton(main)
        self.exit_btn.setGeometry(QtCore.QRect(1830, 30, 30, 30))
        self.exit_btn.setMinimumSize(QtCore.QSize(30, 30))
        self.exit_btn.setMaximumSize(QtCore.QSize(161, 161))
        self.exit_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(178, 39, 39,100);\n"
"    color: #FFFFFF;\n"
"    padding: 2px;\n"
"    font: bold 15px;\n"
"    border-width: 6px;\n"
"    border-radius: 10px;\n"
"    border-color: #2752B8;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #827397;\n"
"}")
        self.exit_btn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-close-window-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_btn.setIcon(icon6)
        self.exit_btn.setIconSize(QtCore.QSize(20, 20))
        self.exit_btn.setObjectName("exit_btn")
        self.minimize_btn = QtWidgets.QPushButton(main)
        self.minimize_btn.setGeometry(QtCore.QRect(1780, 30, 30, 30))
        self.minimize_btn.setMinimumSize(QtCore.QSize(30, 30))
        self.minimize_btn.setMaximumSize(QtCore.QSize(161, 161))
        self.minimize_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 229, 32,100);\n"
"    color: #FFFFFF;\n"
"    padding: 2px;\n"
"    font: bold 15px;\n"
"    border-width: 6px;\n"
"    border-radius: 10px;\n"
"    border-color: #2752B8;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #827397;\n"
"}")
        self.minimize_btn.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-subtract-16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimize_btn.setIcon(icon7)
        self.minimize_btn.setIconSize(QtCore.QSize(30, 30))
        self.minimize_btn.setObjectName("minimize_btn")
        self.label_4 = QtWidgets.QLabel(main)
        self.label_4.setGeometry(QtCore.QRect(270, 80, 61, 61))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/icons/icons/icons8-inbox-65s.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.layoutWidget = QtWidgets.QWidget(main)
        self.layoutWidget.setGeometry(QtCore.QRect(190, 110, 111, 151))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.inbox_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.inbox_btn.setMinimumSize(QtCore.QSize(100, 100))
        self.inbox_btn.setMaximumSize(QtCore.QSize(161, 161))
        self.inbox_btn.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: rgb(85, 132, 220,100);\n"
"    color: #FFFFFF;\n"
"    padding: 2px;\n"
"    font: bold 15px;\n"
"    border-width: 6px;\n"
"    border-radius: 10px;\n"
"    border-color: #2752B8;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #EFEAD8;\n"
"}")
        self.inbox_btn.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-inbox-65.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.inbox_btn.setIcon(icon8)
        self.inbox_btn.setIconSize(QtCore.QSize(100, 100))
        self.inbox_btn.setObjectName("inbox_btn")
        self.verticalLayout_6.addWidget(self.inbox_btn)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem12 = QtWidgets.QSpacerItem(44, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem12)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setMaximumSize(QtCore.QSize(161, 16777215))
        font = QtGui.QFont()
        font.setFamily("Cairo")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        spacerItem13 = QtWidgets.QSpacerItem(44, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem13)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.label_3.raise_()
        self.label.raise_()
        self.frame.raise_()
        self.logOut_btn.raise_()
        self.groupBox.raise_()
        self.exit_btn.raise_()
        self.minimize_btn.raise_()
        self.inbox_btn.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.label_4.raise_()

        self.retranslateUi(main)
        QtCore.QMetaObject.connectSlotsByName(main)

    def retranslateUi(self, main):
        _translate = QtCore.QCoreApplication.translate
        main.setWindowTitle(_translate("main", "Form"))
        self.label.setText(_translate("main", "الوجهه الرئيسيه"))
        self.label_11.setText(_translate("main", "متطلبات اوامر الشغل"))
        self.label_9.setText(_translate("main", "العملاء"))
        self.label_12.setText(_translate("main", "متابعه اوامر الشغل"))
        self.label_10.setText(_translate("main", "اوامر الشغل المنتهيه"))
        self.label_6.setText(_translate("main", "امر الشغل"))
        self.groupBox.setTitle(_translate("main", "User Info"))
        self.label_2.setText(_translate("main", "User Name :"))
        self.username_lbl.setText(_translate("main", "Abdel-Rahman"))
        self.label_7.setText(_translate("main", "Session time :"))
        self.sessionTime_lbl.setText(_translate("main", "2 m"))
        self.label_8.setText(_translate("main", "inbox"))
import app_resources_rc
