# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/main_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main(object):
    def setupUi(self, main):
        main.setObjectName("main")
        main.resize(1037, 662)
        self.gridLayout_2 = QtWidgets.QGridLayout(main)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(399, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(main)
        self.label.setMaximumSize(QtCore.QSize(271, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(399, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 3, 1, 1)
        self.frame = QtWidgets.QFrame(main)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.workOrder_btn = QtWidgets.QPushButton(self.frame)
        self.workOrder_btn.setMinimumSize(QtCore.QSize(165, 85))
        self.workOrder_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.workOrder_btn.setStyleSheet("font: 11pt \"Acumin Pro\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(50, 85, 127);\n"
"\n"
" border-radius: 12px;\n"
"")
        self.workOrder_btn.setObjectName("workOrder_btn")
        self.gridLayout_3.addWidget(self.workOrder_btn, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 0, 4, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 0, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 0, 6, 1, 1)
        self.clients_btn = QtWidgets.QPushButton(self.frame)
        self.clients_btn.setMinimumSize(QtCore.QSize(165, 81))
        self.clients_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.clients_btn.setStyleSheet("font: 11pt \"Acumin Pro\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(50, 85, 127);\n"
"\n"
" border-radius: 12px;\n"
"")
        self.clients_btn.setObjectName("clients_btn")
        self.gridLayout_3.addWidget(self.clients_btn, 0, 5, 1, 1)
        self.followOrders_btn = QtWidgets.QPushButton(self.frame)
        self.followOrders_btn.setMinimumSize(QtCore.QSize(165, 81))
        self.followOrders_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.followOrders_btn.setStyleSheet("font: 11pt \"Acumin Pro\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(50, 85, 127);\n"
"\n"
" border-radius: 12px;\n"
"")
        self.followOrders_btn.setObjectName("followOrders_btn")
        self.gridLayout_3.addWidget(self.followOrders_btn, 0, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem6, 0, 2, 1, 1)
        self.finishedOrders_btn = QtWidgets.QPushButton(self.frame)
        self.finishedOrders_btn.setMinimumSize(QtCore.QSize(161, 85))
        self.finishedOrders_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.finishedOrders_btn.setStyleSheet("font: 11pt \"Acumin Pro\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(50, 85, 127);\n"
"\n"
" border-radius: 12px;\n"
"")
        self.finishedOrders_btn.setObjectName("finishedOrders_btn")
        self.gridLayout_4.addWidget(self.finishedOrders_btn, 0, 3, 1, 1)
        self.ordersReq_btn = QtWidgets.QPushButton(self.frame)
        self.ordersReq_btn.setMinimumSize(QtCore.QSize(161, 85))
        self.ordersReq_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ordersReq_btn.setStyleSheet("font: 11pt \"Acumin Pro\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(50, 85, 127);\n"
"\n"
" border-radius: 12px;\n"
"")
        self.ordersReq_btn.setObjectName("ordersReq_btn")
        self.gridLayout_4.addWidget(self.ordersReq_btn, 0, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem7, 0, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem8, 0, 4, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_4, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 1, 0, 1, 4)
        self.logOut_btn = QtWidgets.QPushButton(main)
        self.logOut_btn.setMinimumSize(QtCore.QSize(50, 50))
        self.logOut_btn.setMaximumSize(QtCore.QSize(50, 50))
        self.logOut_btn.setStyleSheet("background-color: rgb(255, 170, 255,4);")
        self.logOut_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/images/icons8-logout-80.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logOut_btn.setIcon(icon)
        self.logOut_btn.setIconSize(QtCore.QSize(50, 50))
        self.logOut_btn.setObjectName("logOut_btn")
        self.gridLayout_2.addWidget(self.logOut_btn, 0, 0, 1, 1)

        self.retranslateUi(main)
        QtCore.QMetaObject.connectSlotsByName(main)

    def retranslateUi(self, main):
        _translate = QtCore.QCoreApplication.translate
        main.setWindowTitle(_translate("main", "Form"))
        self.label.setText(_translate("main", "الوجهه الرئيسيه"))
        self.workOrder_btn.setText(_translate("main", "امر الشغل"))
        self.clients_btn.setText(_translate("main", "العملاء"))
        self.followOrders_btn.setText(_translate("main", "متابعه اوامر الشغل"))
        self.finishedOrders_btn.setText(_translate("main", "اوامر الشغل المنتهيه"))
        self.ordersReq_btn.setText(_translate("main", "متطلبات اوامر الشغل"))
import app_resources_rc
